#ifndef PROGRAM_SETTING_H_
#define PROGRAM_SETTING_H_

#define OLED_CLEAR_RANGE    8
#define OLED_INFO_POSITION  0
#define OLED_BAL_POSITION   10
#define OLED_IDM_POSITION   40
#define OLED_PMM_POSITION   50


#endif